CREATE TABLE IF NOT EXISTS `ASSIGNMENT` (
  `ASSIGNMENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BILLING_ID` INT(11) NOT NULL,
  `VEHICLE_ID` INT(5) NOT NULL,
  `DRIVER_ID` INT(11) NOT NULL,
  `CUSTOMER_ID` INT(10) NOT NULL,
  `DATE` DATE NOT NULL,
  `TIME` INT(6) NOT NULL,
  PRIMARY KEY (`ASSIGNMENT_ID`)
  ) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `BILLING` (
  `BILLING_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ASSIGNMENT_ID` INT(11) NOT NULL,
  `AMOUNT` INT(10) NOT NULL,
  PRIMARY KEY (`BILLING_ID`)
  )ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `BOOKING` (
  `BOOKING_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `VEHICLE_TYPE` VARCHAR(25) NOT NULL,
  `DATE` DATE NOT NULL,
  `TIME` TIME NOT NULL,
  `LOCATION` VARCHAR(25) NOT NULL,
  `CUSTOMER_ID` VARCHAR (25), 
  PRIMARY KEY (`BOOKING_ID`)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `CUSTOMER_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(200) NOT NULL,
  `LAST_NAME` VARCHAR(200) NOT NULL,
  `CONTACT_ID` INT(10) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `LOGIN` (
  `USER_ID` VARCHAR(10) NOT NULL,
  `PASSWORD` VARCHAR(10) NOT NULL,
   PRIMARY KEY (`USER_ID`)
  ) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `VEHICLE` (
  `VEHICLE_ID` INT(5) NOT NULL AUTO_INCREMENT,
  `REG_NUMBER` VARCHAR(25) NOT NULL,
  `VEHICLE_TYPE` VARCHAR(25) NOT NULL,
  `MODEL` VARCHAR(25) NOT NULL,
  `AVAILABILITY` CHAR(1) NOT NULL,
   PRIMARY KEY (`VEHICLE_ID`)
) ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS `CONTACT` (
  `CONTACT_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `HOME_PH` INT(10) NOT NULL,
  `MOBILE_PH` INT(10) NOT NULL,
  `E_MAIL` VARCHAR (100) NOT NULL,
  `ADDRESS` VARCHAR (100) NOT NULL,
  PRIMARY KEY (`CONTACT_ID`)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `DRIVER` (
  `DRIVER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(20) NOT NULL,
  `LAST_NAME` VARCHAR(20) NOT NULL,
  `AGE` INT(3) NOT NULL,
  `CONTACT_ID` INT(10) NOT NULL,
  `AVAILABILITY` CHAR(1) NOT NULL,
  PRIMARY KEY (`DRIVER_ID`)
) ENGINE=INNODB;